///////////////////////////////////////////////////////////////////////////////
//  Icarus Game Engine
//  Copyright © 2011 Timothy Leonard
///////////////////////////////////////////////////////////////////////////////	
// Generated by update_version.py
// 28-08-2012 00:39
///////////////////////////////////////////////////////////////////////////////	
// WARNING: Do not modify this file in any way, it's format is assumed by
//			several python scripts used during building!
///////////////////////////////////////////////////////////////////////////////	
#pragma once

#ifndef _VERSION_H_
#define _VERSION_H_

namespace AutoVersion
{
	static const char DAY[] = "28";
	static const char MONTH[] = "8";
	static const char YEAR[] = "2012";
	
	static const char HOUR[] = "0";
	static const char MINUTE[] = "39";
	static const char SECOND[] = "52";
	
	static const char STATUS[] = "Alpha";
	static const char STATUS_SHORT[] = "a";

	static const long MAJOR = 0;
	static const long MINOR = 1;
	static const long BUILD = 32;
	static const long REVISION = 20;

	static const char FULLVERSION_STRING[] = "0.1.32.20a";

	static const long TOTAL_BUILDS = 3220;
}

#endif // _VERSION_H_
